version: '3.8'

services:
  db:
      image: mysql:8.0
      environment:
        MYSQL_DATABASE: myStoreDB
        MYSQL_ROOT_PASSWORD: ROOT123!dsgdg#xzvb!aew
      ports:
        - "3306:3306"
      volumes:
        - db-data:/var/lib/mysql
      networks:
        - app-network
        
  app:
    image: spring-server
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/myStoreDB
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=ROOT123!dsgdg#xzvb!aew
      - RSA_PRIVATE_KEY=classpath:certs/private.pem
      - RSA_PUBLIC_KEY=classpath:certs/public.pem
      - SECURITY_REQUIRE_SSL=true
      - SERVER_SSL_KEY_STORE=classpath:certs/keystore.p12
      - SERVER_SSL_KEY_STORE_PASSWORD=0505235003
      - SERVER_SSL_KEYSTORE_TYPE=PKCS12
      - SERVER_SSL_KEY_ALIAS=tomcat
      - STRIPE_WEBHOOK_SECRET=whsec_ELog8ltYT4wggD8Dme6XWiN8dmA4FF65
      - STRIPE_SECRET_KEY=sk_test_51MDZpHFkDhKHmlx9ou5z6uikqTB2mUKrtPMezOpBzFThalkqztWDRvessvwq5l0o8oxmQppQHU6st3Xbra3qUtAS00uMXiHnh6
      - BASE_URL=https://mystore.alahideb.me/
      - SERVER_PORT=8443
    ports:
      - "8443:8443"
    depends_on:
      - db
    networks:
      - app-network

  

  web:
    image: my-static-website
    ports:
      - "80:80"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  db-data:
