version: '3.8'

services:
  db:
      image: mysql:8.0
      environment:
        MYSQL_DATABASE: myStoreDB
        MYSQL_ROOT_PASSWORD: ROOT123!dsgdg#xzvb!aew
      ports:
        - "3306:3306"
      volumes:
        - db-data:/var/lib/mysql
      networks:
        - app-network
        
  app:
    image: spring-server
    ports:
      - "8443:8443"
    depends_on:
      - db
    networks:
      - app-network

  

  web:
    image: my-static-website
    ports:
      - "80:80"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  db-data:
